### PR TITLE
Add db schema

### PR DESCRIPTION
**Pull request by cheevu-RS**

### CODE REVIEW

**Review by sandy9999 — APPROVED** [review]

**Comment by suicide3** [comment]
What have you done sandy. It's impossible to survive.depression & I are best friends.Have you ever thought about my parents.

**Comment by suicide3** [comment]
Why??? Have you ever thought what I had gone through in life & trying to overcome.My texts without thought harnesses you, any idea what you made me to deal with.

**Comment by suicide3** [comment]
My entire life got spoiled bc of you.

**Comment by suicide3** [comment]
I may have no idea how many more days I can bear this depression.Already 5 years beared.No idea days I may leave.please don't do this to others.Before judging , make sure person may not be dealing with depression like me.

**Comment by suicide3** [comment]
Stay happy that all I want.Ignore my texts they aredepression generated.

**Comment by suicide3** [comment]
I was dealing with depression & anxiety issues, frustration so staying in quaters with mother.U made me impossible to recover.
 Stay happy.

**Comment by suicide3** [comment]
Do you really have humanity feeling. I may had passed away just bc of parents wants to leave.

**Comment by suicide3** [comment]
From last 5 years am in depression now you had given lifetime.St ramesh made it extreme.
Have you noticed difference b/w  my texts & mayank& Aaryan ,my were anxiety generator.
I thought Bas degree mil jiye or fir mba dosto ki saath kar lenge , you spoil everything.

**Comment by suicide3** [comment]
Left with no option other than dropping out nit Trichy.If you don't believe about depression ,I have all treatment & medicine certificate from last 3.5years.

**Comment by suicide3** [comment]
I was dealing with surve depression so stay with my mother.

**Comment by suicide3** [comment]
Definitely being in depression ,my behaviour & thought will be worst.Max. of my friends knows about it.Depression in nitt was st. Ramesh.

**Comment by suicide3** [comment]
You don't have humanity. I was texting you,roopa bc of depression till now No idea what I had texted. I can't come & say I love you sandhya, I was not in state to do so.I require some person to o talk being in depression.

**Comment by suicide3** [comment]
I had gone through tough phase in life sandhya from seeing dad completely burnt ,death of loved one,etc,etc .
 You made me impossible to survive. Everything was fine after completing nitt I may be with my friends & may gone for mba or startup. I may be happy after completing degree.
 Do you know sikar person have some of best startup in country.

**Comment by suicide3** [comment]
What was my mistake , speaking bad words is my habit ,I speak at home too who gives such punishment for this issue.I have feelings to suicide. Why??
 Today I able to sleep 3 hr only.

**Comment by suicide3** [comment]
I don't know how to speak , speaks bad words , will speak like I will kill you,etc,etc but I never ever knowingly hurted anyone. You have no idea what ST RAMESH made me suffer.

**Comment by suicide3** [comment]
Why??

**Comment by suicide3** [comment]
Why??
 If you told me sachin please don't text I may had stopped.
  I know I am dealing with depression ,I just requires someone to talk that it complicated.

**Comment by suicide3** [comment]
Now my body vibrates am struggling to leave single single minute I will think SHALL I die...

**Comment by suicide3** [comment]
Depression gonna kill me. That was your love , attachment,etc,etc . I have no feeling being in depression but you were normal.
 Why??? Atleast take allegations back.So that I can leave peacefully.
 Tell your father & mother to talk them , they only can save me nothing can't be expected from devil 😈 like you. no feelings.

**Comment by suicide3** [comment]
How you had born to such kind & good people, atleast learn from them.I texted worst  & worst to your mother still she is so kind to me. Be like them nothing gonna achieve from such hatred.

**Comment by suicide3** [comment]
I have no feeling to do wrong with you but please don't do what you did to me. Be kind.
  I may die at any time.

**Comment by suicide3** [comment]
Nikhil,Parag bhaiya ,jyoti di is helping to cope up with mental health without there support I may had attempted suicide much early.
 Have ever thought what my parents have to go through.

**Comment by suicide3** [comment]
They may had died if I had attempted suicide .
  Parents can't leave without children.
 Give me any punishment you want for my behaviour but I can't leave with such allegations.you have to speak truth.

**Comment by suicide3** [comment]
Depression depression was prt of my life from last 5 years ,now you made it forever in life.

**Comment by suicide3** [comment]
If your brother in my place then you may had realised how good depression is every second you will be struggling to leave.you head will be heavy,compressed, fails to breathe , body vibrated , no idea when I slept properly last time. You want to leave this world ,then you worried about parents.

**Comment by suicide3** [comment]
Anyway You have no problem if I die bc you are emotional ess & heartless. No feelings.

**Comment by suicide3** [comment]
Save me.Be kind. Speak truth. Not in state to deal with it.

**Comment by suicide3** [comment]
That was your love 😄. To drag me into depression forever.

**Comment by suicide3** [comment]
Already last 5 years I know What all things I had gone through.

**Comment by suicide3** [comment]
Why Sandy??...

**Comment by suicide3** [comment]
If you want to do wrong then I will come to Chennai & do whatever you want.

**Comment by suicide3** [comment]
Happy birthday in advance.

**Pull request merged**
